name: workflow
on:
  push:
    branches:
      - master
jobs:
  docker_comp:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Docker compose
        run: docker-compose up
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10.4
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Test
        run: python postgres.py

  build_and_pub:
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.POSTGRES_LOGIN }}
      NAME: ${{ secrets.POSTGRES_NAME }}
    steps:
      - name: Login to docker
        run: echo ${{ secrets.POSTGRES_TOKEN }} | docker login -u ${{ secrets.POSTGRES_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
      - name: Push image to docker
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}